services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: "unless-stopped"

  generator:
    build:
      context: ./DataGeneration/
    container_name: generator
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  live_server:
    build:
      context: ./RealtimeServer/
    container_name: liveServer
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - generator
    ports:
      - "8000:8000"
      - "8000:8000/tcp"
