services: 
  app:
    build: .
    container_name: f1_telemetry_app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  
  mongo:
    image: mongo
    container_name: f1_telemetry_mongo
    command: mongod --quiet
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
    driver: local